## **PROJECT: PREDICTING USING KNN (SUPERVISED MACHINE LEARNING ALGORITHM)**

*MAKING PREDICTIONS USING THE IRIS DATASET*



**Importing the neccessary libraries**

In [1]:
import pandas as pd
import numpy as np
import sklearn
from sklearn.model_selection import train_test_split

**Importing the in-build dataset from the sklearn module**

In [2]:
from sklearn.datasets import load_iris
iris_dataset = load_iris()

**Getting the description of the iris dataset & EDA**

In [3]:
print("keys of iris_dataset: \n{}".format(iris_dataset.keys()))

keys of iris_dataset: 
dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names', 'filename'])


In [4]:
print(iris_dataset['DESCR'][:193] + "\n...")

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, pre
...


In [6]:
val = iris_dataset["DESCR"]
start_val = val[:200]
print(start_val + "\n...")

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive
...


In [8]:
print("targer_names: \n{}". format(iris_dataset['target_names']))

targer_names: 
['setosa' 'versicolor' 'virginica']


In [10]:
print("Feature_names: \n{}".format(iris_dataset['feature_names']))

Feature_names: 
['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


In [12]:
print("Type of data: {}".format(type(iris_dataset['data'])))

Type of data: <class 'numpy.ndarray'>


In [14]:
print("Shape of the data :{}".format(iris_dataset['data'].shape))

Shape of the data :(150, 4)


In [16]:
print("First five rows of the data: \n{}".format(iris_dataset['data'][:5]))

First five rows of the data: 
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]


In [17]:
print("type of target: {}".format(type(iris_dataset['target'])))

type of target: <class 'numpy.ndarray'>


In [18]:
print("Shape of target: {}".format(iris_dataset['target'].shape))

Shape of target: (150,)


In [19]:
print("Target : \n{}".format(iris_dataset['target']))

Target : 
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


0 : setosa
1: versicolor
2: virginica

**Training and testing the dataset**

In [20]:
X_train, X_test, y_train, y_test = train_test_split(iris_dataset['data'], iris_dataset['target'], random_state = 0)

In [21]:
print("X_train shape:{}".format(X_train.shape))
print("X_test shape:{}".format(X_test.shape))
print("y_train shape:{}".format(y_train.shape))
print("y_test shape:{}".format(y_test.shape))


X_train shape:(112, 4)
X_test shape:(38, 4)
y_train shape:(112,)
y_test shape:(38,)


In [24]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors = 1)

In [26]:
knn.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=1, p=2,
                     weights='uniform')

**Making Predictions**
Here we will make prediction of a flower which has sepal length of 5cm, sepal width of 2.9cm, petal length of 1cm and petal width of 0.2cm.

In [27]:
X_new = np.array([[5,2.9,1,0.2]])
print("X_new.shape: {}".format(X_new.shape))

X_new.shape: (1, 4)


In [29]:
prediction = knn.predict(X_new)
print("Prediction :{}".format(prediction))
print("predicted target name: {}".format(iris_dataset['target_names'][prediction]))

Prediction :[0]
predicted target name: ['setosa']


**Evaluating The Model**

In [30]:
y_pred = knn.predict(X_test)
print("Test set prediction: \n {}".format(y_pred))

Test set prediction: 
 [2 1 0 2 0 2 0 1 1 1 2 1 1 1 1 0 1 1 0 0 2 1 0 0 2 0 0 1 1 0 2 1 0 2 2 1 0
 2]


In [31]:
print("TEST SET SCORE: {}".format(np.mean(y_pred == y_test)))

TEST SET SCORE: 0.9736842105263158
